keys:
  - &server_homelab-00 age1uuv0r00xsglqu3ec0cr9kxxeym9csvwcannvz28xc29mwx0mwsgsu2smt2
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *server_homelab-00
